**Векторизация и оптимизация кода**

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b # Быстрое сложение массивов

**Создание массива и операции с массивами**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
print(result)

[5 7 9]


In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

In [11]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data)
print(std_dev)

1.4142135623730951


**Доступ к элементам массива**

In [26]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [20]:
print(m[1, 0])

5


In [24]:
print(m[1, :])

[[5 6 7 8]]


In [22]:
print(m[:, 2])

[[3]
 [7]
 [5]]


In [ ]:
print(m[1, 2:])

In [ ]:
print(m[0:2, 1])

In [ ]:
print(m[0:2, 1:3])

In [ ]:
print(cols = [0, 1, 3])

**Расчет статистики по данным в массиве**

In [28]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [30]:
print(type(m))

<class 'numpy.matrix'>


In [32]:
print(m.shape)

(3, 4)


In [ ]:
print(m.max())

In [34]:
print(m.max(axis=1))

[[4]
 [8]
 [9]]
