**Векторизация и оптимизация кода**

In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b # Быстрое сложение массивов

**Создание массива и операции с массивами**

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2 # [5, 7, 9]
print(result)

[5 7 9]


In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

In [11]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data)
print(std_dev)

1.4142135623730951


**Доступ к элементам массива**

In [26]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [20]:
print(m[1, 0])

5


In [24]:
print(m[1, :])

[[5 6 7 8]]


In [22]:
print(m[:, 2])

[[3]
 [7]
 [5]]


In [ ]:
print(m[1, 2:])

In [ ]:
print(m[0:2, 1])

In [ ]:
print(m[0:2, 1:3])

In [ ]:
print(cols = [0, 1, 3])

**Расчет статистики по данным в массиве**

In [5]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [30]:
print(type(m))

<class 'numpy.matrix'>


In [32]:
print(m.shape)

(3, 4)


In [8]:
print(m.max())

9


In [7]:
print(m.max(axis=1))

[[4]
 [8]
 [9]]


In [6]:
print(np.arange(1, 5, 0.5))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
a = [[1, 2], [3, 4]]
print(np.matrix(a))

In [ ]:
print(np.zeros((3, 4)))

In [ ]:
print(np.eye(3))

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.ravel(A))

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.ravel(A, order='C'))

In [ ]:
print(np.ravel(A, order='F'))

In [19]:
np.random.permutation(7)
a = ['a', 'b', 'c', 'd', 'e']
np.random.permutation(a)
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [20]:
arr_mix = np.random.permutation(arr)
print(arr_mix)

[10.   7.5  5.   2.5  0. ]


In [22]:
index_mix = np.random.permutation(len(arr_mix))
print(index_mix)

[3 0 1 4 2]


**Матрицы**

In [23]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


In [24]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [25]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)

[1. 1. 1. 1. 1.]


In [26]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [27]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [28]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [32]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [33]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Трансонирование матрицы**

In [36]:
A = np.matrix('1 2 3; 4 5 6')
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


*Свойство 1.* Дважды транспонированная матрица равна исходной матрице.

In [37]:
A = np.matrix('1 2 3; 4 5 6')
print(A)
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


*Свойство 2.* Транспонирование суммы матриц равно сумме транспонированных
матриц:

In [38]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


*Свойство 3.* Транспонирование произведения матриц равно произведению
транспонированных матриц расставленных в обратном порядке:

In [39]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L) 
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


*Свойство 4.* Транспонирование произведения матрицы на число равно
произведению этого числа на транспонированную матрицу:

In [40]:
A = np.matrix('1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


*Свойство 5.* Определители исходной и транспонированной матрицы совпадают:

In [41]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(f"{A_det:.9f}")
print(f"{A_T_det:.9f}")

-2.000000000
-2.000000000


**Действия над матрицами**

In [42]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [44]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [ ]:
A = np.matrix('1 2; 3 4')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

In [45]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


**Сложение матриц**

In [46]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


In [47]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)
print(R)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [48]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [49]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


**Умножение матриц**

In [50]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


In [51]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [52]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [53]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A.dot(B)
R = B.dot(A)
print(L)
print(R)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


**Определитель матрицы**

In [54]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [55]:
np.linalg.det(A)

-14.000000000000009

In [56]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [57]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)
round(np.linalg.det(A), 3)
round(np.linalg.det(B), 3)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


14.0

***Обратная матрица**

In [58]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [59]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


In [60]:
A = np.matrix('1. -3.; 2. 5.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]
[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [61]:
A = np.matrix('1. -3.; 2. 5.')
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
