**Задание 1**

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0.Выведите итоговый массив

In [ ]:
import numpy as np
matr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("начальная матрица:\n", matr)
matr=matr*2
for i in range(3):
    for j in range(3):
        if matr[i,j]>10:
            matr[i,j]=0      
print("Конечная матрица:\n", matr)

**Задание 2**

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив.

In [ ]:
import numpy as np
import random
mas=np.arange(1,100)
mas=np.random.permutation(mas)
mas= mas[:20]
for i in range(20):
    if mas[i]%5==0:
        print (mas[i])
        mas[i]=-1
print(mas)

**Задание 3**

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50/].

- Объедините эти массивы в один двумерный массив (по строкам)
- Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты

In [12]:
import numpy as np
import random
mas1=np.arange(0,50)
mas1=np.random.permutation(mas1)
mas1= mas1[:5]
mas2=np.arange(0,50)
mas2=np.random.permutation(mas2)
mas2= mas2[:5]
print(mas1, mas2)
res=np.vstack((mas1, mas2))
print(f"объединенные:\n {res}")
res=np.split(res,2)
print(f"Разделенные:\n {res}")

[27 37  0  3 20] [31 44 18 21 36]
объединенные:
 [[27 37  0  3 20]
 [31 44 18 21 36]]
Разделенные:
 [array([[27, 37,  0,  3, 20]]), array([[31, 44, 18, 21, 36]])]


**Задание 4**

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [ ]:
import random
mas=np.linspace(-10,10,num=49)
sum=0
sum1=0
sum2=0
for i in range(49):
    sum+=mas[i]
    if mas[i]>0:
        sum1+=mas[i]
    if mas[i]<0:
        sum1+=mas[i]
print(sum,sum1,sum2)

**Задание 5**

Создайте:

- Единичную матрицу размером 4×4
- Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы). 

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [ ]:
import numpy as np
mas=np.eye(4)
mas2=np.diag([5, 10, 15, 20])
print(mas)
print(mas2)

**Задание 6**

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
- Их сумму
- Их разность
- Их поэлементное произведение

In [15]:
import numpy as np
matr1 = np.random.randint(1, 21, size = (3, 3))
matr2 = np.random.randint(1, 21, size = (3, 3))
sum = matr1 + matr2
razn = matr1 - matr2
proiz = matr1 * matr2
print(f"Первоначальные матрицы:\n {matr1},\n{matr2}")
print(f"Сумма:\n{sum}")
print(f"Разность:\n{razn}")
print(f"Произведение:\n{proiz}")

Первоначальные матрицы:
 [[ 6 17 20]
 [19 17  3]
 [ 8  5  6]],
[[ 1 12  5]
 [ 3  7 15]
 [12 13  4]]
Сумма:
[[ 7 29 25]
 [22 24 18]
 [20 18 10]]
Разность:
[[  5   5  15]
 [ 16  10 -12]
 [ -4  -8   2]]
Произведение:
[[  6 204 100]
 [ 57 119  45]
 [ 96  65  24]]


**Задание 7**

Создайте две матрицы NumPy:

- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение ( @ или np.dot ) и выведите результат.

In [1]:
import numpy as np
matr1 = np.random.randint(1, 11, size = (2, 3))
matr2 = np.random.randint(1, 11, size = (3, 2))
print(f"Первая матрица:\n {matr1}")
print(f"Вторая матрица:\n {matr2}")
print(f"Ответ: \n", np.dot(matr1, matr2) )

Первая матрица:
 [[10 10  5]
 [ 3  5  7]]
Вторая матрица:
 [[ 4 10]
 [ 7  1]
 [ 5  5]]
Ответ: 
 [[135 135]
 [ 82  70]]


**Задание 8**

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:

- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица
вырождена)

Используйте функции np.linalg.det и np.linalg.inv .


In [15]:
import numpy as np
matr1 = np.random.randint(1, 11, size = (3, 3))
print(f"Исходная матрица:\n {matr1}")
print(f"определитель: {np.linalg.det(matr1)}\nОбратная матрица:\n {np.linalg.inv(matr1)}")

Первая матрица:
 [[ 4  1  1]
 [ 6 10  3]
 [ 1  5  9]]
определитель: 269.0000000000002
Обратная матрица:
 [[ 0.27881041 -0.01486989 -0.0260223 ]
 [-0.18959108  0.13011152 -0.02230483]
 [ 0.07434944 -0.07063197  0.12639405]]


**Задание 9**

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от
1 до 50. Выведите:

- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов на главной диагонали)

Используйте np.trace для нахождения следа.

In [26]:
import numpy as np
matr1 = np.random.randint(1, 51, size = (4, 4))
print(f"Исходная матрица:\n {matr1}")
print(f"Транспонированная матрица:\n {np.transpose(matr1)} \n след матрицы:\n {np.trace(matr1)}")

Исходная матрица:
 [[ 9 36 42 20]
 [23 46 40 46]
 [13 42 12 14]
 [34 10 26 47]]
Транспонированная матрица:
 [[ 9 23 13 34]
 [36 46 42 10]
 [42 40 12 26]
 [20 46 14 47]] 
 след матрицы:
 114


**Задание 10**

Решите систему линейных уравнений вида:

⎧2x + 3y − z = 5
⎨4x − y + 2z = 6
⎩−3x + 5y + 4z = −2

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат.

In [28]:
import numpy as np 
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]])
B = np.array([5, 6, -2])
x = np.linalg.solve(A, B)
print(f"Решение системы:")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")
print(f"z = {x[2]:.2f}")

Решение системы:
x = 1.64
y = 0.58
z = 0.01


**Задание 11**

Решите индивидуальное задание согласно варианта. Каждое задание
предусматривает построение системы линейных уравнений. Решите полученную
систему уравнений с использованием библиотеки NumPy. Для решения системы
используйте метод Крамера и матричный метод. Сравните полученные
результаты, с результатами, полученными с помощью np.linalg.solve .

**Вариант 20**

Для создания нового металлического сплава
используются три вида металлов. В первом металле содержится 60% железа,
во втором — 70%, в третьем — 80%. Нужно получить 100 кг сплава с 72%
железа. При этом второго металла должно быть в два раза больше, чем
первого. Сколько килограммов каждого металла нужно взять?

**Решение**

Составим систему уравнений.
Пусть в первом метале 0.6x железа, во втором 0.7y, в третьем 0.8z :

⎧x+y+z=100         
⎨0.6x+0.7y+0.8z=72
⎩y=2x


In [1]:
import numpy as np  
#Метод Крамера
def kram(A, B):
    A1 = np.linalg.det(A)
    result = []
    for i in range(A.shape[0]):
        Ai = A.copy()
        Ai[:, i] = B
        result.append(np.linalg.det(Ai) / A1)
    return result
A = np.array([
    [1, 1, 1],
    [0.6, 0.7, 0.8],
    [-2, 1, 0,]])
B = np.array([100, 72, 0])
s=kram(A, B)
print(f"Решение методом Крамера:\n ")
for i, sol in enumerate(s, start = 1):
    print(f"x{i}: {sol}")
    
x = np.linalg.solve(A, B)
print(f"\nРешение системы:\n")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")
print(f"z = {x[2]:.2f}")

Решение методом Крамера:
 
x1: 20.000000000000014
x2: 40.00000000000004
x3: 40.00000000000006

Решение системы:

x = 20.00
y = 40.00
z = 40.00
